import { Flashcard, FlashcardDeck } from '../types';

export const FLASHCARD_DECKS_DATA: FlashcardDeck[] = [
  {
    id: 'deck_cardio',
    title: 'Cardiology High-Yield',
    category: 'Cardiology',
    cardCount: 6,
    dueTodayCount: 4,
    masteryPercentage: 78
  },
  {
    id: 'deck_emergency',
    title: 'Emergency Red Flags',
    category: 'Emergency Medicine',
    cardCount: 5,
    dueTodayCount: 3,
    masteryPercentage: 65
  },
  {
    id: 'deck_pharm',
    title: 'Toxicology & Antidotes',
    category: 'Pharmacology',
    cardCount: 5,
    dueTodayCount: 5,
    masteryPercentage: 50
  }
];

export const FLASHCARDS_DATA: Flashcard[] = [
  {
    id: 'fc1',
    deckId: 'deck_cardio',
    topicTitle: 'Acute Myocardial Infarction',
    category: 'Cardiology',
    frontPrompt: 'What are the 3 physical exam findings of Right Ventricular (RV) Infarction, and what common medication is strictly contraindicated?',
    backAnswer: 'Triad: Hypotension + Clear Lung Fields + Elevated JVD.\n\nStrictly Contraindicated: Nitroglycerin (and diuretics), because RV infarction is heavily dependent on preload!',
    clinicalHint: 'Think about chamber compliance and systemic venous backpressure.',
    repetitionCount: 3,
    intervalDays: 4,
    easeFactor: 2.5,
    dueDate: '2026-09-13',
    isBookmarked: true
  },
  {
    id: 'fc2',
    deckId: 'deck_cardio',
    topicTitle: 'Congestive Heart Failure',
    category: 'Cardiology',
    frontPrompt: 'What clinical sign is represented by an S3 gallop, and what physiologic event generates it?',
    backAnswer: 'Sign of volume overload & elevated LV filling pressures.\n\nGenerated by rapid passive ventricular filling of blood decelerating into an already dilated, stiff, or overfilled left ventricle in early diastole.',
    clinicalHint: '“Kentucky” cadence (S1 - S2 - S3).',
    repetitionCount: 2,
    intervalDays: 2,
    easeFactor: 2.4,
    dueDate: '2026-09-13',
    isBookmarked: false
  },
  {
    id: 'fc3',
    deckId: 'deck_cardio',
    topicTitle: 'Cardiac Tamponade',
    category: 'Cardiology',
    frontPrompt: 'What is Beck\'s Triad for acute cardiac tamponade?',
    backAnswer: '1. Hypotension (low arterial blood pressure)\n2. Distended Neck Veins (elevated JVP)\n3. Muffled / Distant Heart Sounds\n\n(Often accompanied by Pulsus Paradoxus > 10 mmHg drop in systolic BP during inspiration).',
    clinicalHint: '3 signs of pericardial fluid compressing the heart.',
    repetitionCount: 1,
    intervalDays: 1,
    easeFactor: 2.3,
    dueDate: '2026-09-13',
    isBookmarked: true
  },
  {
    id: 'fc4',
    deckId: 'deck_cardio',
    topicTitle: 'Heart Failure GDMT',
    category: 'Cardiology',
    frontPrompt: 'What are the "Four Pillars" of Guideline-Directed Medical Therapy (GDMT) shown to reduce mortality in HFrEF?',
    backAnswer: '1. ARNI (Sacubitril/Valsartan) or ACEi/ARB\n2. Evidence-based Beta-blocker (Carvedilol, Metoprolol succinate, Bisoprolol)\n3. MRA (Spironolactone or Eplerenone)\n4. SGLT2 inhibitor (Dapagliflozin or Empagliflozin)',
    clinicalHint: 'Four distinct neurohormonal and metabolic pathways.',
    repetitionCount: 4,
    intervalDays: 7,
    easeFactor: 2.6,
    dueDate: '2026-09-15',
    isBookmarked: false
  },
  {
    id: 'fc5',
    deckId: 'deck_emergency',
    topicTitle: 'Intracranial Hypertension',
    category: 'Emergency Medicine',
    frontPrompt: 'What is Cushing\'s Triad, and what life-threatening condition does it herald?',
    backAnswer: 'Triad:\n1. Severe Hypertension (widened pulse pressure)\n2. Bradycardia\n3. Irregular / Cheyne-Stokes respirations\n\nHeralds: Imminent brain herniation from severely increased intracranial pressure (ICP)!',
    clinicalHint: 'CNS response to brainstem ischemia.',
    repetitionCount: 2,
    intervalDays: 3,
    easeFactor: 2.5,
    dueDate: '2026-09-13',
    isBookmarked: true
  },
  {
    id: 'fc6',
    deckId: 'deck_emergency',
    topicTitle: 'Pulmonary Embolism',
    category: 'Emergency Medicine',
    frontPrompt: 'What is the most frequent 12-lead ECG finding in acute pulmonary embolism?',
    backAnswer: 'Sinus Tachycardia (present in > 40% of cases).\n\n(Note: The classic S1Q3T3 pattern of acute right heart strain is specific but seen in only ~10–15% of cases!)',
    clinicalHint: 'Don\'t be tricked by the famous board eponym!',
    repetitionCount: 1,
    intervalDays: 1,
    easeFactor: 2.4,
    dueDate: '2026-09-13',
    isBookmarked: false
  },
  {
    id: 'fc7',
    deckId: 'deck_pharm',
    topicTitle: 'Toxicology Antidotes',
    category: 'Pharmacology',
    frontPrompt: 'What is the specific antidote for Beta-blocker overdose, and what is its molecular mechanism?',
    backAnswer: 'Antidote: Intravenous Glucagon (followed by High-Dose Insulin Euglycemia / HIE).\n\nMechanism: Glucagon activates adenylyl cyclase via non-adrenergic receptors, bypassing blocked beta receptors to increase intracellular cAMP and myocardial contractility.',
    clinicalHint: 'Bypasses the beta-adrenergic receptor to stimulate cAMP.',
    repetitionCount: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    dueDate: '2026-09-13',
    isBookmarked: false
  },
  {
    id: 'fc8',
    deckId: 'deck_pharm',
    topicTitle: 'Toxicology Antidotes',
    category: 'Pharmacology',
    frontPrompt: 'What is the reversal agent for unfractionated heparin, and how does it work?',
    backAnswer: 'Protamine Sulfate.\n\nMechanism: Highly positively charged (basic) peptide that binds stoichiometrically to strongly negatively charged (acidic) heparin molecules, creating an inactive stable salt complex.',
    clinicalHint: 'A basic protein extracted from salmon sperm.',
    repetitionCount: 1,
    intervalDays: 2,
    easeFactor: 2.5,
    dueDate: '2026-09-13',
    isBookmarked: false
  }
];
